export interface LanguageProfile {
	languageIds: string[];
	keywords: Set<string>;
	identifierPattern: RegExp;
	stripStringsAndComments: (text: string) => string;
	normalizeSymbol?: (symbol: string) => string;
}

const genericIdentifierPattern = /[A-Za-z_][A-Za-z0-9_]*/g;

const cLikeKeywords = [
	'abstract',
	'as',
	'async',
	'await',
	'base',
	'bool',
	'boolean',
	'break',
	'case',
	'catch',
	'char',
	'class',
	'const',
	'continue',
	'default',
	'delegate',
	'do',
	'double',
	'else',
	'enum',
	'event',
	'extends',
	'extern',
	'false',
	'final',
	'finally',
	'float',
	'for',
	'foreach',
	'goto',
	'if',
	'implements',
	'import',
	'in',
	'int',
	'interface',
	'internal',
	'is',
	'long',
	'namespace',
	'new',
	'null',
	'object',
	'operator',
	'out',
	'override',
	'package',
	'params',
	'private',
	'protected',
	'public',
	'readonly',
	'ref',
	'return',
	'sbyte',
	'sealed',
	'short',
	'sizeof',
	'static',
	'string',
	'struct',
	'super',
	'switch',
	'this',
	'throw',
	'throws',
	'true',
	'try',
	'typeof',
	'uint',
	'ulong',
	'unchecked',
	'unsafe',
	'ushort',
	'using',
	'var',
	'virtual',
	'void',
	'volatile',
	'while',
];

const pythonKeywords = [
	'and',
	'as',
	'assert',
	'async',
	'await',
	'break',
	'class',
	'continue',
	'def',
	'del',
	'elif',
	'else',
	'except',
	'False',
	'finally',
	'for',
	'from',
	'global',
	'if',
	'import',
	'in',
	'is',
	'lambda',
	'None',
	'nonlocal',
	'not',
	'or',
	'pass',
	'raise',
	'return',
	'True',
	'try',
	'while',
	'with',
	'yield',
];

const rustKeywords = [
	'as',
	'async',
	'await',
	'break',
	'const',
	'continue',
	'crate',
	'dyn',
	'else',
	'enum',
	'extern',
	'false',
	'fn',
	'for',
	'if',
	'impl',
	'in',
	'let',
	'loop',
	'match',
	'mod',
	'move',
	'mut',
	'pub',
	'ref',
	'return',
	'Self',
	'self',
	'static',
	'struct',
	'super',
	'trait',
	'true',
	'type',
	'unsafe',
	'use',
	'where',
	'while',
];

const goKeywords = [
	'break',
	'case',
	'chan',
	'const',
	'continue',
	'default',
	'defer',
	'else',
	'fallthrough',
	'for',
	'func',
	'go',
	'goto',
	'if',
	'import',
	'interface',
	'map',
	'nil',
	'package',
	'range',
	'return',
	'select',
	'struct',
	'switch',
	'type',
	'var',
];

const phpKeywords = [
	'abstract',
	'and',
	'array',
	'as',
	'break',
	'callable',
	'case',
	'catch',
	'class',
	'clone',
	'const',
	'continue',
	'declare',
	'default',
	'die',
	'do',
	'echo',
	'else',
	'elseif',
	'empty',
	'enddeclare',
	'endfor',
	'endforeach',
	'endif',
	'endswitch',
	'endwhile',
	'eval',
	'exit',
	'extends',
	'final',
	'finally',
	'fn',
	'for',
	'foreach',
	'function',
	'global',
	'if',
	'implements',
	'include',
	'include_once',
	'instanceof',
	'insteadof',
	'interface',
	'isset',
	'list',
	'match',
	'namespace',
	'new',
	'or',
	'print',
	'private',
	'protected',
	'public',
	'readonly',
	'require',
	'require_once',
	'return',
	'static',
	'switch',
	'throw',
	'trait',
	'try',
	'unset',
	'use',
	'var',
	'while',
	'xor',
	'yield',
];

const swiftKeywords = [
	'associatedtype',
	'as',
	'break',
	'case',
	'catch',
	'class',
	'continue',
	'default',
	'defer',
	'deinit',
	'do',
	'else',
	'enum',
	'extension',
	'fallthrough',
	'false',
	'fileprivate',
	'for',
	'func',
	'guard',
	'if',
	'import',
	'in',
	'init',
	'inout',
	'internal',
	'is',
	'let',
	'nil',
	'open',
	'operator',
	'private',
	'protocol',
	'public',
	'repeat',
	'return',
	'Self',
	'self',
	'static',
	'struct',
	'subscript',
	'super',
	'switch',
	'throw',
	'throws',
	'true',
	'try',
	'typealias',
	'var',
	'where',
	'while',
];

export const LANGUAGE_PROFILES: LanguageProfile[] = [
	{
		languageIds: ['python'],
		keywords: new Set(pythonKeywords),
		identifierPattern: genericIdentifierPattern,
		stripStringsAndComments: stripPythonStringsAndComments,
	},
	{
		languageIds: ['csharp', 'java', 'c', 'cpp'],
		keywords: new Set(cLikeKeywords),
		identifierPattern: genericIdentifierPattern,
		stripStringsAndComments: stripCLikeStringsAndComments,
	},
	{
		languageIds: ['rust'],
		keywords: new Set(rustKeywords),
		identifierPattern: genericIdentifierPattern,
		stripStringsAndComments: stripCLikeStringsAndComments,
	},
	{
		languageIds: ['go'],
		keywords: new Set(goKeywords),
		identifierPattern: genericIdentifierPattern,
		stripStringsAndComments: stripCLikeStringsAndComments,
	},
	{
		languageIds: ['php'],
		keywords: new Set(phpKeywords),
		identifierPattern: /\$?[A-Za-z_][A-Za-z0-9_]*/g,
		stripStringsAndComments: stripPhpStringsAndComments,
	},
	{
		languageIds: ['swift'],
		keywords: new Set(swiftKeywords),
		identifierPattern: /`?[A-Za-z_][A-Za-z0-9_]*`?/g,
		stripStringsAndComments: stripCLikeStringsAndComments,
		normalizeSymbol: (symbol) => symbol.replace(/^`|`$/g, ''),
	},
];

export function getLanguageProfile(languageId: string): LanguageProfile | undefined {
	return LANGUAGE_PROFILES.find((profile) => profile.languageIds.includes(languageId));
}

export function stripCLikeStringsAndComments(text: string): string {
	return text
		.replace(/\/\*[\s\S]*?\*\//g, preserveNewlines)
		.replace(/\/\/.*$/gm, '')
		.replace(/'(?:\\.|[^'\\])*'/g, preserveNewlines)
		.replace(/"(?:\\.|[^"\\])*"/g, preserveNewlines)
		.replace(/`(?:\\.|[^`\\])*`/g, preserveNewlines);
}

export function stripPythonStringsAndComments(text: string): string {
	return text
		.replace(/(?:[rRuUbBfF]{0,2})'''[\s\S]*?'''/g, preserveNewlines)
		.replace(/(?:[rRuUbBfF]{0,2})"""[\s\S]*?"""/g, preserveNewlines)
		.replace(/#.*/gm, '')
		.replace(/(?:[rRuUbBfF]{0,2})'(?:\\.|[^'\\])*'/g, preserveNewlines)
		.replace(/(?:[rRuUbBfF]{0,2})"(?:\\.|[^"\\])*"/g, preserveNewlines);
}

function stripPhpStringsAndComments(text: string): string {
	return stripCLikeStringsAndComments(text)
		.replace(/#.*$/gm, '');
}

function preserveNewlines(value: string): string {
	return value.replace(/[^\r\n]/g, ' ');
}
